# EC3365 Final Project

In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

In [35]:
# Import data sets and clean data
emissions = pd.read_csv("https://raw.githubusercontent.com/pforwork/EC3365/main/emissions.csv", delimiter=',', skiprows=1)
emissions

,Series Key,INTL.4008-8-USOH-MMTCD.A,Series Key.1,INTL.4008-8-ARG-MMTCD.A,Series Key.2,INTL.4008-8-BEN-MMTCD.A,Series Key.3,INTL.4008-8-BHR-MMTCD.A,Series Key.4,INTL.4008-8-BRN-MMTCD.A,...,Series Key.225,INTL.4008-8-SOM-MMTCD.A,Series Key.226,INTL.4008-8-SYR-MMTCD.A,Series Key.227,INTL.4008-8-TUN-MMTCD.A,Series Key.228,INTL.4008-8-WSM-MMTCD.A,Series Key.229,INTL.4008-8-DEUW-MMTCD.A
0,Series Name,"CO2 emissions, U.S. Territories, Annual",Series Name,"CO2 emissions, Argentina, Annual",Series Name,"CO2 emissions, Benin, Annual",Series Name,"CO2 emissions, Bahrain, Annual",Series Name,"CO2 emissions, Brunei, Annual",...,Series Name,"CO2 emissions, Somalia, Annual",Series Name,"CO2 emissions, Syria, Annual",Series Name,"CO2 emissions, Tunisia, Annual",Series Name,"CO2 emissions, Samoa, Annual",Series Name,"CO2 emissions, Germany, West, Annual"
1,Units,MMTCD,Units,MMTCD,Units,MMTCD,Units,MMTCD,Units,MMTCD,...,Units,MMTCD,Units,MMTCD,Units,MMTCD,Units,MMTCD,Units,MMTCD
2,Frequency,A,Frequency,A,Frequency,A,Frequency,A,Frequency,A,...,Frequency,A,Frequency,A,Frequency,A,Frequency,A,Frequency,A
3,1980,0,1980,93,1980,0.4,1980,7.8,1980,4.5,...,1980,1.1,1980,16,1980,8.5,1980,(s),1980,736
4,1981,0,1981,91,1981,0.4,1981,8.9,1981,4.7,...,1981,1.3,1981,17,1981,9.3,1981,(s),1981,691
5,1982,0,1982,94,1982,0.3,1982,9.3,1982,5,...,1982,1.3,1982,17,1982,8.7,1982,0.1,1982,686
6,1983,0,1983,94,1983,0.4,1983,9.9,1983,4,...,1983,1.2,1983,20,1983,10,1983,0.1,1983,681
7,1984,0,1984,98,1984,0.4,1984,9.6,1984,3.6,...,1984,1.3,1984,22,1984,11,1984,0.1,1984,705
8,1985,0,1985,92,1985,0.5,1985,11,1985,4.3,...,1985,1.3,1985,23,1985,11,1985,0.1,1985,726
9,1986,0,1986,104,1986,0.5,1986,12,1986,2.8,...,1986,1.4,1986,24,1986,12,1986,0.1,1986,751
10,1987,0,1987,106,1987,0.4,1987,15,1987,4.5,...,1987,1.1,1987,28,1987,11,1987,0.1,1987,745
11,1988,0,1988,108,1988,0.5,1988,13,1988,4,...,1988,1.1,1988,29,1988,12,1988,0.1,1988,735
12,1989,0,1989,107,1989,0.5,1989,13,1989,4.6,...,1989,1.1,1989,31,1989,13,1989,0.1,1989,721
13,1990,0,1990,99,1990,0.6,1990,14,1990,3.9,...,1990,1,1990,36,1990,13,1990,0.1,1990,719
14,1991,0,1991,104,1991,0.7,1991,16,1991,3.2,...,1991,0.6,1991,32,1991,11,1991,0.1,1991,--
15,1992,0,1992,106,1992,0.8,1992,14,1992,3.1,...,1992,0.6,1992,33,1992,12,1992,0.1,1992,--
16,1993,0,1993,116,1993,0.8,1993,16,1993,3,...,1993,0.6,1993,38,1993,15,1993,0.1,1993,--
17,1994,0,1994,112,1994,0.9,1994,16,1994,2.9,...,1994,0.6,1994,41,1994,16,1994,0.1,1994,--
18,1995,0,1995,115,1995,1,1995,16,1995,3.5,...,1995,0.6,1995,39,1995,14,1995,0.1,1995,--
19,1996,0,1996,123,1996,1,1996,16,1996,3.5,...,1996,0.6,1996,41,1996,14,1996,0.1,1996,--
20,1997,0,1997,126,1997,1.1,1997,18,1997,3.7,...,1997,0.6,1997,43,1997,17,1997,0.1,1997,--
21,1998,0,1998,134,1998,1.2,1998,19,1998,3.2,...,1998,0.6,1998,47,1998,17,1998,0.1,1998,--
22,1999,0,1999,139,1999,1.3,1999,20,1999,3.6,...,1999,0.6,1999,50,1999,19,1999,0.1,1999,--
23,2000,0,2000,138,2000,1.7,2000,20,2000,3.8,...,2000,0.7,2000,50,2000,19,2000,0.1,2000,--
24,2001,0,2001,127,2001,1.7,2001,21,2001,4.2,...,2001,0.7,2001,49,2001,21,2001,0.1,2001,--
25,2002,0,2002,119,2002,1.7,2002,22,2002,4.9,...,2002,0.7,2002,52,2002,20,2002,0.1,2002,--
26,2003,0,2003,133,2003,2.1,2003,22,2003,5.2,...,2003,0.7,2003,52,2003,20,2003,0.1,2003,--
27,2004,0,2004,140,2004,2.4,2004,23,2004,5.8,...,2004,0.7,2004,52,2004,20,2004,0.2,2004,--
28,2005,0,2005,152,2005,2.5,2005,25,2005,6.6,...,2005,0.7,2005,51,2005,21,2005,0.2,2005,--
29,2006,0,2006,156,2006,3,2006,28,2006,9.8,...,2006,0.8,2006,51,2006,20,2006,0.2,2006,--
30,2007,0,2007,158,2007,3.3,2007,29,2007,10,...,2007,0.8,2007,50,2007,18,2007,0.2,2007,--
31,2008,0,2008,169,2008,3.4,2008,31,2008,11,...,2008,0.9,2008,55,2008,21,2008,0.2,2008,--
32,2009,0,2009,168,2009,4.5,2009,31,2009,7.2,...,2009,0.8,2009,62,2009,18,2009,0.2,2009,--
33,2010,0,2010,186,2010,5.1,2010,31,2010,8.2,...,2010,0.8,2010,65,2010,18,2010,0.3,2010,--
34,2011,0,2011,190,2011,4.7,2011,33,2011,8.5,...,2011,0.8,2011,60,2011,18,2011,0.3,2011,--
35,2012,0,2012,196,2012,4.4,2012,35,2012,8.2,...,2012,0.8,2012,45,2012,19,2012,0.3,2012,--
36,2013,0,2013,197,2013,4.5,2013,39,2013,7.7,...,2013,0.8,2013,31,2013,20,2013,0.3,2013,--
37,2014,0,2014,197,2014,4.8,2014,39,2014,8.6,...,2014,0.8,2014,27,2014,22,2014,0.3,2014,--
38,2015,0,2015,214,2015,5.4,2015,39,2015,9.3,...,2015,0.9,2015,27,2015,23,2015,0.3,2015,--
39,2016,0,2016,214,2016,6.5,2016,39,2016,9.7,...,2016,0.9,2016,26,2016,23,2016,0.3,2016,--
40,2017,0,2017,195,2017,7,2017,39,2017,9.8,...,2017,0.9,2017,26,2017,25,2017,0.3,2017,--
41,2018,0,2018,195,2018,7.7,2018,39,2018,10,...,2018,0.9,2018,31,2018,25,2018,0.3,2018,--
42,2019,0,2019,201,2019,7,2019,42,2019,10,...,2019,0.9,2019,27,2019,24,2019,0.4,2019,--
43,2020,0,2020,167,2020,7.5,2020,42,2020,10,...,2020,0.8,2020,25,2020,22,2020,0.3,2020,--
44,2021,0,2021,199,2021,7.7,2021,42,2021,8.6,...,2021,0.9,2021,26,2021,22,2021,0.3,2021,--

In [20]:
energy = pd.read_csv("https://raw.githubusercontent.com/pforwork/EC3365/main/energyconsumption.csv", delimiter=',', skiprows=1)
energy.fillna(energy.median(), inplace=True)
energy.rename(columns={'Unnamed: 1': 'Country'}, inplace=True)
energy.dropna(subset=['API'], inplace=True)
energy.dropna(how='all', inplace=True)

for col in energy.columns[2:]:
    if energy[col].dtype in ['float64', 'int64']:
        energy[col].fillna(energy[col].median(), inplace=True)
energy

/var/folders/5t/msy6g6h16yb10kd_7l8qdzfw0000gn/T/ipykernel_13809/3719266542.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  energy.fillna(energy.median(), inplace=True)

,API,Country,1980,1981,1982,1983,1984,1985,1986,1987,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,INTL.44-2-AFG-QBTU.A,Afghanistan,0.02658321667756184,0.029949457623843767,0.031897814673808554,0.03902180313163165,0.03920224040186807,0.03827496129519434,0.039111198580053776,0.06306515769145625,...,0.13765027069319372,0.11416576977462783,0.09696120084250569,0.11172582624800645,0.10196781485590371,0.10086123775411128,0.11569819729775732,0.10343658619574822,0.09346919021295572,0.09258890712086146
2,INTL.44-2-ALB-QBTU.A,Albania,0.16298182182124926,0.16204449273682853,0.16284611700217974,0.16933585149179003,0.1704057218202433,0.17005625500667076,0.16607537777033485,0.1666405283961216,...,0.1051279333181231,0.13193111766441915,0.11621639284070061,0.11629730243544255,0.13589570519859817,0.12578047491234484,0.14342046025641697,0.1136090571488556,0.10914868032090533,0.137347715206226
3,INTL.44-2-DZA-QBTU.A,Algeria,0.7806951671133022,0.6633913232329025,0.952188115918025,1.0705618432163024,1.1307867129706235,1.0464182466677772,1.0663009617019872,1.1383186539191739,...,2.098203173382945,2.037584643437122,2.299888435758712,2.3521475403657623,2.3359823797283905,2.365986904617233,2.522119152162065,2.6248730961427658,2.4808107737143397,2.58112331407509
4,INTL.44-2-ASM-QBTU.A,American Samoa,0.0058931124,0.00692647725,0.0096550895,0.00608690425,0.0069454539,0.00650669075,0.006716584,0.0069730088735,...,0.004933530033037225,0.004930590895857226,0.004930528895857227,0.004930145088825,0.00495266140458,0.004957573895818638,0.004957028895818638,0.0049560338958186375,0.00472248254264,0.0054464101348
5,INTL.44-2-AGO-QBTU.A,Angola,0.05836614796628778,0.05786368803134464,0.06200789925058719,0.06629700722242975,0.059894700907251144,0.07376669580030859,0.072853256,0.0751354785,...,0.31073998491839994,0.34776127766959997,0.382763725955,0.399218709765,0.364251516864,0.347458949401,0.35922694644,0.404865374,0.4023175359623359,0.32862841773276713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,INTL.44-2-WAK-QBTU.A,Wake Island,0.01873749337291053,0.018686298035826075,0.018686298035826075,0.018686298035826075,0.01873749337291053,0.0184786725,0.0184786725,0.0184786725,...,0.019373112,0.01932018,0.01932018,0.01931915,0.01932466,0.01932503,0.01939703,0.0194360456,0,0
227,INTL.44-2-ESH-QBTU.A,Western Sahara,0.002365535363412504,0.00235907215203706,0.002573533259077455,0.002573533259077455,0.002580584035129722,0.002787994364057425,0.002693073879,0.002738024505,...,0.00365732828021918,0.003647335580000002,0.003647335580000002,0.00364424,0.0036360172,0.003712095580127827,0.003712095580127827,0.0037120955,0.003544423257701849,0.0037399657966206644
228,INTL.44-2-YEM-QBTU.A,Yemen,0.09549226626503785,0.09734761084333841,0.1142776301185542,0.10581262048162848,0.13156712240979637,0.1460214162647722,0.14051916,0.139347145,...,0.24776793666822494,0.3496784894573262,0.3310014225538624,0.17875471999684137,0.14309344374738195,0.13208612625189264,0.12299834163757001,0.15887768911390782,0.12029246139402255,0.12154550392186414
229,INTL.44-2-ZMB-QBTU.A,Zambia,0.13311664167592396,0.1324782683524794,0.135388943093979,0.13482301200356028,0.13046882774657492,0.12923196814160648,0.12862584046167308,0.11922015920644374,...,0.15680578500948522,0.16627198891752895,0.17846441604291333,0.17270328555090977,0.16287091968688217,0.18899722403224778,0.2126726399156923,0.18713948417800577,0.20015130475187246,0.22716664593513097
230,INTL.44-2-ZWE-QBTU.A,Zimbabwe,0.1414723741419828,0.1423668569379908,0.13490705532101982,0.13931682987471733,0.1393448630494655,0.1464299031845133,0.16378602676516257,0.18493809359719854,...,0.1858936243630224,0.18895891592781563,0.18631645549933867,0.1864772275489146,0.15917198887933118,0.1544217350376225,0.17678110338960365,0.157367768525088,0.14329889638637208,0.14380604162114935

In [21]:
countries_df = gpd.read_file("https://raw.githubusercontent.com/pforwork/EC3365/main/world-countries.json")
countries_df

,id,name,geometry
0,AFG,Afghanistan,"POLYGON ((61.21082 35.65007, 62.23065 35.27066..."
1,AGO,Angola,"MULTIPOLYGON (((16.32653 -5.87747, 16.57318 -6..."
2,ALB,Albania,"POLYGON ((20.59025 41.85540, 20.46317 41.51509..."
3,ARE,United Arab Emirates,"POLYGON ((51.57952 24.24550, 51.75744 24.29407..."
4,ARG,Argentina,"MULTIPOLYGON (((-65.50000 -55.20000, -66.45000..."
...,...,...,...
172,PSE,West Bank,"POLYGON ((35.54566 32.39399, 35.54525 31.78251..."
173,YEM,Yemen,"POLYGON ((53.10857 16.65105, 52.38521 16.38241..."
174,ZAF,South Africa,"POLYGON ((31.52100 -29.25739, 31.32556 -29.401..."
175,ZMB,Zambia,"POLYGON ((32.75937 -9.23060, 33.23139 -9.67672..."
176,ZWE,Zimbabwe,"POLYGON ((31.19141 -22.25151, 30.65986 -22.151..."

In [53]:
pwt = pd.read_csv("https://raw.githubusercontent.com/pforwork/EC3365/main/pwt1001.csv")
pwt = pwt[pwt['year'] >= 1980]   
pwt['emp'] = pwt['emp'].astype(float)
pwt.drop(columns=['countrycode', 'currency_unit'], inplace=True)
pwt.sort_values(by=['country', 'year'], inplace=True)
pwt.fillna(method='ffill', inplace=True)
pwt.fillna(method='bfill', inplace=True)
pwt = pwt.dropna().reset_index(drop=True)
pwt

,country,year,rgdpe,rgdpo,pop,emp,avh,hc,ccon,cda,...,csh_x,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_n,pl_k
0,Albania,1980,9975.0,9965.0,3.0,1.0,"1,974",2.0,7981.0,9522.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Albania,1981,10321.0,10363.0,3.0,1.0,"1,974",2.0,8146.0,9928.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,Albania,1982,10415.0,10392.0,3.0,1.0,"1,974",2.0,8296.0,10357.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Albania,1983,10801.0,10742.0,3.0,1.0,"1,974",2.0,8762.0,10598.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,Albania,1984,10968.0,10857.0,3.0,1.0,"1,974",2.0,9060.0,10644.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7315,Zimbabwe,2015,40142.0,39799.0,14.0,6.0,"2,132",3.0,44249.0,47325.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,2.0
7316,Zimbabwe,2016,41875.0,40963.0,14.0,7.0,"2,132",3.0,43292.0,46404.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,2.0
7317,Zimbabwe,2017,44672.0,44317.0,14.0,7.0,"2,132",3.0,46114.0,49458.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,2.0
7318,Zimbabwe,2018,44325.0,43421.0,14.0,7.0,"2,132",3.0,46198.0,49665.0,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,2.0
7319,Zimbabwe,2019,42296.0,40827.0,15.0,7.0,"2,132",3.0,43962.0,47129.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0

## Analysis